### ISSUE TITLE
Getting an error urllib.error.HTTPError: HTTP Error 404: Not found when I run client3.py

### ISSUE THREAD

**Issue by RaswithaNarla66** [insidesherpa/JPMC-tech-task-1-PY3#101]
Hi,

C:\Users\Narla.Raswitha\JPMC-tech-task-1-py3>python client3.py
Traceback (most recent call last):
  File "client3.py", line 52, in <module>
    quotes = json.loads(urllib.request.urlopen(QUERY.format(random.random())).read())
  File "C:\Python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\Python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python36\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\Python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Python36\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not found

I am getting this error when I run my client3.py file and I have runner server3.py in separate cmd and client3.py in the separate cmd and after running server first I have executed client file. Caan anyone help me out with this please.
![Screenshot (1496)](https://user-images.githubusercontent.com/56207644/82741028-35792b80-9d1c-11ea-8648-13a210bf373b.png)

**Comment by RaswithaNarla66** [comment]
can anyone help me with this issue please.

**Comment by Dhanvvi99** [comment]
I faced the same issue but then I changed the port 8080 to 8085 in server3.py and client3.py (if u are using server.py or client.py, the solution will be the same). change the port 8080 to 8085 where ever you encounter that in the whole file. and then try again.

**Comment by RaswithaNarla66** [comment]
ya, it worked for me Thanks a lot.

**Comment by mokshajaiswal** [comment]
how to change it

**Comment by Dhanvvi99** [comment]
> how to change it

see,  go to the folder where you cloned your repository. Then open the server3.py and client3.py for python 3. If you are using python 2.7.x then the file name would be normally client.py and server.py. Open it in any text editor and search for port 8080 and erase that and replace it with 8085. Same for both the client and server. Then again start the process from the beginning. Hope it works.

**Comment by mokshajaiswal** [comment]
thanks it worked
