### ISSUE TITLE
Error with client3.py

### ISSUE THREAD

**Issue by snroeung** [insidesherpa/JPMC-tech-task-1-PY3#102]
C:\Users\saren\JPMC-tech-task-1-py3>python client3.py
Traceback (most recent call last):
  File "C:\Users\saren\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 1319, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\saren\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\saren\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\saren\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\saren\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1004, in _send_output
    self.send(msg)
  File "C:\Users\saren\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 944, in send
    self.connect()
  File "C:\Users\saren\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 915, in connect
    self.sock = self._create_connection(
  File "C:\Users\saren\AppData\Local\Programs\Python\Python38-32\lib\socket.py", line 808, in create_connection
    raise err
  File "C:\Users\saren\AppData\Local\Programs\Python\Python38-32\lib\socket.py", line 796, in create_connection
    sock.connect(sa)
**ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "client3.py", line 52, in <module>
    quotes = json.loads(urllib.request.urlopen(QUERY.format(random.random())).read())
  File "C:\Users\saren\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\saren\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\saren\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\saren\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\saren\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 1348, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Users\saren\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 1322, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>

I'm getting specifically a connection refused error. I already changed both files from 8080 to 8085

**Comment by VegetableDog118** [comment]
I have the same problem have you fixed it :)
