### ISSUE TITLE
When I run command python server3.py and python client3.py ,I got the following error of code

### ISSUE THREAD

**Issue by HemantLaddha** [insidesherpa/JPMC-tech-task-1-PY3#140]
C:\Users\K6IN\JPMC-tech-task-1-py3>python server3.py
Traceback (most recent call last):
  File "server3.py", line 26, in <module>
    import dateutil.parser
ModuleNotFoundError: No module named 'dateutil'

C:\Users\K6IN\JPMC-tech-task-1-py3>python client3.py
Traceback (most recent call last):
  File "C:\Users\K6IN\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\K6IN\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\K6IN\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\K6IN\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\K6IN\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1006, in _send_output
    self.send(msg)
  File "C:\Users\K6IN\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 946, in send
    self.connect()
  File "C:\Users\K6IN\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 917, in connect
    self.sock = self._create_connection(
  File "C:\Users\K6IN\AppData\Local\Programs\Python\Python38\lib\socket.py", line 808, in create_connection
    raise err
  File "C:\Users\K6IN\AppData\Local\Programs\Python\Python38\lib\socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "client3.py", line 52, in <module>
    quotes = json.loads(urllib.request.urlopen(QUERY.format(random.random())).read())
  File "C:\Users\K6IN\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\K6IN\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\K6IN\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\K6IN\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\K6IN\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 1379, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Users\K6IN\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>

**Comment by HemantLaddha** [comment]
I dont know how to fix it

**Comment by HemantLaddha** [comment]
for solving the dateutil problem I hit the command as shown below but it shows the following error

C:\Users\K6IN\JPMC-tech-task-1-py3>pip install dateutil
ERROR: Could not find a version that satisfies the requirement dateutil (from versions: none)
ERROR: No matching distribution found for dateutil

**Comment by HemantLaddha** [comment]
C:\Users\K6IN\JPMC-tech-task-1-py3>pip --version
pip 20.1.1 from c:\users\k6in\appdata\local\programs\python\python38\lib\site-packages\pip (python 3.8)

**Comment by HemantLaddha** [comment]
for server3.py I solved by running command
pip install python-dateutil

**Comment by HemantLaddha** [comment]
but for client3.py many errors are there ...

**Comment by twinkle055** [comment]
Actually try opening another Administrator Command Prompt while the one for server3.py is open. Don't close it and type the command for client3.py in the other prompt. It should work fine.

**Comment by francisco50** [comment]
change the port from 8080 to 8085
