### ISSUE TITLE
unknown issue with setting up development environment

### ISSUE THREAD

**Issue by iv4nd** [insidesherpa/JPMC-tech-task-1-PY3#15]
Exception happened during processing of request from ('127.0.0.1', 63786)
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "server3.py", line 213, in do_GET
    get(self, routes)
  File "server3.py", line 202, in get
    req_handler.wfile.write(bytes(data,  encoding = 'utf-8'))
TypeError: str() takes at most 1 argument (2 given)
----------------------------------------

**Comment by iv4nd** [comment]
Apologies. It seemed to have been syntax error.
