### ISSUE TITLE
Error in Opening Client file "python3 client3.py"

### ISSUE THREAD

**Issue by vikrantgoswami** [insidesherpa/JPMC-tech-task-1-PY3#185]
I am working in Linux environment and I have completed all the requirements for task 1 but when I run the command `python3 client3.py` I am getting the following error: 

_Traceback (most recent call last):
  File "client3.py", line 53, in <module>
    quotes = json.loads(urllib.request.urlopen(QUERY.format(random.random())).read())
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'_

The server3.py is opening at port 8080 but client3.py is showing above error. I have not made any changes to the client3.py till now but still it is not opening. So please help me resolve this issue.

**Comment by harpreetdhing** [comment]
try with python client3.py if you have python version>3
