### ISSUE TITLE
encounter error when running client3.py

### ISSUE THREAD

**Issue by jdyeux** [insidesherpa/JPMC-tech-task-1-PY3#194]
When I run client3.py, I got the following message in terminal:

Traceback (most recent call last):
  File "client3.py", line 52, in <module>
    quotes = json.loads(urllib.request.urlopen(QUERY.format(random.random())).read())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable

I have read several posts that suggested changing the port from 8080 to 8085, but it didn't work. Any help would be appreciated!

**Comment by jdyeux** [comment]
nvm, I encountered this because I was having my VPN on.

**Comment by ghost** [comment]
can you please give suggestions to answer this
