### ISSUE TITLE
 [WinError 10013] 

### ISSUE THREAD

**Issue by charitha-iddum** [insidesherpa/JPMC-tech-task-1-PY3#195]
Traceback (most recent call last):
  File "server3.py", line 320, in <module>
    run(App())
  File "server3.py", line 214, in run
    server = ThreadedHTTPServer((host, port), RequestHandler)
  File "C:\Users\chari\AppData\Local\Programs\Python\Python38-32\lib\socketserver.py", line 452, in __init__
    self.server_bind()
  File "C:\Users\chari\AppData\Local\Programs\Python\Python38-32\lib\http\server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "C:\Users\chari\AppData\Local\Programs\Python\Python38-32\lib\socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

**Comment by hkstone14** [comment]
Hi Charitha,

You can change port number from 8080 to 8085 in server and client files.
server3.py --> line 205 --> port = 8085

**Comment by The-Real-Thisas** [comment]
Keep in mind to make the correct changes to the client URL to reflect the changes to the port.

```python3
QUERY = "http://localhost:8080/query?id={}"
```
to
```python3
QUERY = "http://localhost:8085/query?id={}"
```
