### ISSUE TITLE
Having trouble running client terminal on python3

### ISSUE THREAD

**Issue by rvelarden** [insidesherpa/JPMC-tech-task-1-PY3#199]
When I type python client3.py to open my client terminal I get this:
Traceback (most recent call last):
  File "client3.py", line 21, in <module>
    import urllib.request
ImportError: No module named request

**Comment by The-Real-Thisas** [comment]
When you get an error it's often useful to try to understand it.

`Traceback (most recent call last):`- Shows that it is a traceback.

`File "client3.py", line 21, in`- In the file 'client3.py', in line 21

`import urllib.request` - The line of code that has failed

`ImportError: No module named request` - ImportError suggesting that there is an error during import of a module 

Using this it is possible to enumerate that the likely step to debugging the issue is to see if you have the module installed. 

Try running:
```bash
python3 -m pip install requests
```
