### ISSUE TITLE
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by arya177** [insidesherpa/JPMC-tech-task-1-PY3#212]
C:\Users\Admin\JP Morgan\JPMC-tech-task-1-py3>python server3.py
Traceback (most recent call last):
  File "C:\Users\Admin\JP Morgan\JPMC-tech-task-1-py3\server3.py", line 320, in <module>
    run(App())
  File "C:\Users\Admin\JP Morgan\JPMC-tech-task-1-py3\server3.py", line 214, in run
    server = ThreadedHTTPServer((host, port), RequestHandler)
  File "C:\hp\Python39\lib\socketserver.py", line 452, in __init__
    self.server_bind()
  File "C:\hp\Python39\lib\http\server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "C:\hp\Python39\lib\socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

C:\Users\Admin\JP Morgan\JPMC-tech-task-1-py3>python client3.py
Traceback (most recent call last):
  File "C:\Users\Admin\JP Morgan\JPMC-tech-task-1-py3\client3.py", line 52, in <module>
    quotes = json.loads(urllib.request.urlopen(QUERY.format(random.random())).read())
  File "C:\hp\Python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\hp\Python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\hp\Python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\hp\Python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\hp\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\hp\Python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by sharmila02** [comment]
same error did you find any solution?

**Comment by pavani2322** [comment]
i also got same error how to find solution?
