### ISSUE TITLE
HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by rahulbordoloi** [insidesherpa/JPMC-tech-task-1-PY3#32]
Each Time I run my Server-Side Code with Admin CMD, This shows up-
Traceback (most recent call last):
  File "client3.py", line 52, in <module>
    quotes = json.loads(urllib.request.urlopen(QUERY.format(random.random())).read())
  File "D:\Program Files\Anaconda\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Program Files\Anaconda\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "D:\Program Files\Anaconda\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\Program Files\Anaconda\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "D:\Program Files\Anaconda\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "D:\Program Files\Anaconda\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

**Comment by rahulbordoloi** [comment]
Found out the Solution.
