### ISSUE TITLE
Server is not running

### ISSUE THREAD

**Issue by bideeen** [insidesherpa/JPMC-tech-task-1-PY3#4]
This what Isee when I type python server3.py 

Traceback (most recent call last):
  File "server3.py", line 320, in <module>
    run(App())
  File "server3.py", line 214, in run
    server = ThreadedHTTPServer((host, port), RequestHandler)
  File "/home/bideen/anaconda3/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/home/bideen/anaconda3/lib/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/home/bideen/anaconda3/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

**Comment by jbf-insidesherpa** [comment]
@bideeen just want to confirm if you're running this on your local machine?

That error means something is already listening on port 8080 on your machine. Either you already ran the server3.py on a separate terminal and forgot it's running OR some other application of yours is using that port.

To fix this, you have to kill the process (aka free up the port) that's using port 8080. Depending on your operating system there are a number of ways to do this. From what I can guess you're either running on Linux or Mac OS. Ive left links below that you can follow in order to free up your port 8080 so you can retry running server3.py

Linux:
https://stackoverflow.com/questions/9346211/how-to-kill-a-process-on-a-port-on-ubuntu

Mac:
https://www.devacron.com/how-to-find-and-kill-a-process-on-port-8080-on-mac/

Hope this helps.

Let me know if you've resolved the issue on your end
