### ISSUE TITLE
A huge exception occured on running client3.py

### ISSUE THREAD

**Issue by kumarishivanisingh14** [insidesherpa/JPMC-tech-task-1-PY3#56]
This issue occured when i was setting up environment to do tasks (task 1).
Help me to fix it. I am a beginner.

C:\Users\Shivani>cd JPMC-tech-task-1-py3

C:\Users\Shivani\JPMC-tech-task-1-py3>python client3.py
Traceback (most recent call last):
  File "C:\Users\Shivani\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 1319, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\Shivani\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Shivani\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Shivani\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Shivani\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1004, in _send_output
    self.send(msg)
  File "C:\Users\Shivani\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 944, in send
    self.connect()
  File "C:\Users\Shivani\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 915, in connect
    self.sock = self._create_connection(
  File "C:\Users\Shivani\AppData\Local\Programs\Python\Python38\lib\socket.py", line 808, in create_connection
    raise err
  File "C:\Users\Shivani\AppData\Local\Programs\Python\Python38\lib\socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "client3.py", line 52, in <module>
    quotes = json.loads(urllib.request.urlopen(QUERY.format(random.random())).read())
  File "C:\Users\Shivani\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Shivani\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\Shivani\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\Shivani\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\Shivani\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 1348, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Users\Shivani\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 1322, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>

C:\Users\Shivani\JPMC-tech-task-1-py3>
![Screenshot (25)](https://user-images.githubusercontent.com/43853444/81203210-5257f400-8fe5-11ea-94e0-f5f073afe06a.png)

**Comment by iamprafful** [comment]
You are getting this error because no server is running on port 8080
Try ruining server first using `python server3.py `

**Comment by Anjali-Kadiyala** [comment]
I got a similar error. This occurred because I did not run the server. Before client3.py, run server3.py

**Comment by shivampatil98** [comment]
Is it taking too long to start server on 8080 ?

**Comment by rdagrawal** [comment]
> Is it taking too long to start server on 8080 ?

No, it takes hardly 1-2 min to start the server

Just run server.py in the administrator command window
once you got msg like " HTTP server started on port 8080" then go to another command window and run client.py.

NOTE: don't close server.py
