### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by iamprafful** [insidesherpa/JPMC-tech-task-1-PY3#59]
Getting this issue while running `python server3.py`
```
Traceback (most recent call last):
  File "f:/JP Morgan Chase/JPMC-tech-task-1-py3/server3.py", line 319, in <module>
    generate_csv()
  File "f:/JP Morgan Chase/JPMC-tech-task-1-py3/server3.py", line 151, in generate_csv
    writer.writerow([t, stock, side, order, size])
TypeError: a bytes-like object is required, not 'str'
```

**Comment by iamprafful** [comment]
I copied content from `/JPMC-tech-task-1-py3/test.csv` to the `test.csv` of root folder and it worked
