### ISSUE TITLE
running py server3.py and py client3.py gives error

### ISSUE THREAD

**Issue by pratcode1616** [insidesherpa/JPMC-tech-task-1-PY3#98]
I have python version 3.8.2
I have changed directory to the JPMC-tech-task-1-py3 folder. I have also installed python-dateutil file and added its address to path on system environment variables.
Initially on running  `py server3.py` it gave the error:

> Traceback (most recent call last):
>   File "server3.py", line 26, in <module>
>     import dateutil.parser
> ModuleNotFoundError: No module named 'dateutil'

But then I manually searched for dateutil file, copied and pasted it to JPMC-tech-task-1-py3 file. I again tried to run server3 using the above command. This time the error was like this:

> Traceback (most recent call last):
>   File "server3.py", line 26, in <module>
>     import dateutil.parser
>   File "C:\me\insidesherpa\JPMC-tech-task-1-py3\dateutil\parser\__init__.py", line 2, in <module>
>     from ._parser import parse, parser, parserinfo, ParserError
>   File "C:\me\insidesherpa\JPMC-tech-task-1-py3\dateutil\parser\_parser.py", line 42, in <module>
>     import six
> ModuleNotFoundError: No module named 'six'

On executing `py client3.py`, the error looks like this:

> Traceback (most recent call last):
  File "C:\me\admin\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 1319, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\me\admin\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\me\admin\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\me\admin\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\me\admin\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1004, in _send_output
    self.send(msg)
  File "C:\me\admin\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 944, in send
    self.connect()
  File "C:\me\admin\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 915, in connect
    self.sock = self._create_connection(
  File "C:\me\admin\AppData\Local\Programs\Python\Python38-32\lib\socket.py", line 808, in create_connection
    raise err
  File "C:\me\admin\AppData\Local\Programs\Python\Python38-32\lib\socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
>   File "client3.py", line 52, in <module>
>     quotes = json.loads(urllib.request.urlopen(QUERY.format(random.random())).read())
>   File "C:\me\admin\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 222, in urlopen
>     return opener.open(url, data, timeout)
>   File "C:\me\admin\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 525, in open
>     response = self._open(req, data)
>   File "C:\me\admin\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 542, in _open
>     result = self._call_chain(self.handle_open, protocol, protocol +
>   File "C:\me\admin\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 502, in _call_chain
>     result = func(*args)
>   File "C:\me\admin\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 1348, in http_open
>     return self.do_open(http.client.HTTPConnection, req)
>   File "C:\me\admin\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 1322, in do_open
>     raise URLError(err)
> urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>

Please provide solution for the same.

**Comment by HemantLaddha** [comment]
did you get any sol. of client3.py because i have the same error as you have?

**Comment by anikettiwariii** [comment]
Hey, did you solve it? I have the same issues
